### PR TITLE
fix: empty command (#7)

### LINKED ISSUE #7: Empty string command
Hi! First, thanks for this amazing project :)

So, I tried it on my phone using termux and zsh + oh-my-zsh and it works but for some reason there's this empty string command, it's the first one on the second picture.

### PR DESCRIPTION
**Pull request by luckasRanarison**
Closes #7.

### CODE REVIEW

**Comment by YiNNx** [comment]
Thanks for the fix! I’ll check it later

**Comment by luckasRanarison** [comment]
Oh, wait I think changing the Regex would be a better solution

Update: Why did you capture the newline in 
`(?:[^#\n]|\n)`? This could also cause an empty command.

```rust
static ref RE_BASH_HISTORY: Regex = Regex::new(r"(\d+)\n((?:[^#\n]|\n)+)").unwrap();
```

**Comment by YiNNx** [comment]
Maybe another approach is to refactor the Command::parse_line() function rather than modifying the regex parser's result? The Command::parse() function should be modified to verify if the line of command is empty or contains a valid command, such as combined commands like `echo something &&`

**Comment by YiNNx** [comment]
🤔 the new regex expression works for the empty line, too. But the Command::parse_line() function should also be fixed to handle the empty command in the filled line of combined commands or lines that are filled but not contain an invalid command.

**Comment by YiNNx** [comment]
> Update: Why did you capture the newline in
(?:[^#\n]|\n)? This could also cause an empty command.

I'm really sorry, but I'm struggling with my finals right now and might not be able to get back to you until Thursday :(

**Comment by luckasRanarison** [comment]
> I'm really sorry, but I'm struggling with my finals right now and might not be able to get back to you until Thursday :(

There's no hurry :)

By the way, could I try adding atuin support if you haven't started yet and if you want...

**Comment by YiNNx** [comment]
> By the way, could I try adding atuin support if you haven't started yet and if you want..

Absolutely! I haven't started yet and your contribution would be much appreciated if you're interested. 🙌

**Comment by YiNNx** [comment]
I added some code to improve error handling and condition restrictions for Command::parse_line(), which also help to avoid empty command stats. Now everything looks good to me!
Thanks for the fix and sorry for being a little bit late to review it :(

**Review by YiNNx — APPROVED** [review]

**Comment by YiNNx** [comment]
> Update: Why did you capture the newline in
> (?:[^#\n]|\n)? This could also cause an empty command.

This wounldn't cause the empty command stats, but it is indeed implemented not very elegantly :thinking:  I will submit a PR later to fix it.

**Pull request merged**
