### PR TITLE
chore: rename license file

### PR DESCRIPTION
**Pull request by xj63**
It may be more popular to use LICENSE files.

By default, this link will jump to the file starting with LICENSE.
There is a LICENSE link on the right side of github.
https://github.com/YiNNx/cmd-wrapped#MIT-1-ov-file

Some tools also only use `LICENSE*` files, such as [cargo-aur](https://github.com/fosskers/cargo-aur).

The github documentation also recommends using LICENSE file names in all uppercase letters.
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#determining-the-location-of-your-license

### CODE REVIEW

**Comment by xj63** [comment]
Sorry, the link https://github.com/YiNNx/cmd-wrapped#MIT-1-ov-file cannot jump to the LICENSE interface. It may be my personal problem. License is also valid.

**Comment by xj63** [comment]
I'm sorry for my reckless behavior.
The License is usually valid and there is no need to change it to LICENSE.
It may be better to keep using the License.

By the way, aur already has the [cmd-wrapped](https://aur.archlinux.org/packages/cmd-wrapped) package.

**Comment by YiNNx** [comment]
Apologies for the delayed response (have been struggling with some personal matters :(
I believe renaming the license filename to LICENSE will be a better option, and I simply hadn't noticed the specification earlier. 
I'll reopen this PR and merge it, thanks for your suggestions!

**Comment by YiNNx** [comment]
> By the way, aur already has the [cmd-wrapped](https://aur.archlinux.org/packages/cmd-wrapped) package.

Noticed the aur package page about 2 weeks ago XD. If that was your doing, I really appreciate it!

**Comment by xj63** [comment]
> Noticed the aur package page about 2 weeks ago XD. If that was your doing, I really appreciate it!

Sorry, I am not the author. The author is devome.
I don’t know his contact information. Maybe after you update github release, devome will help you update aur after seeing it. : )

**Pull request merged**
