### PR TITLE
feat: ci & release workflow

### PR DESCRIPTION
**Pull request by luckasRanarison**
Added CI, build, release and publish workflows. Note that the release and publish worflows haven't been tested yet. You'll need to add the environment secrets.
Also linting is currently failing, I'll make a PR to fix it first, if you'd like to add linting.

### CODE REVIEW

**Comment by luckasRanarison** [comment]
Also I've tried building on my branch and the released build are somehow bigger than yours 7-8mb vs 1-2mb for you. Did you apply some optimizations?
Here's one of the artifact I've build using this workflow: https://github.com/luckasRanarison/cmd-wrapped/actions/runs/7683753461/artifacts/1200330615.

**Comment by YiNNx** [comment]
> the released build are somehow bigger than yours 7-8mb vs 1-2mb for you. Did you apply some optimizations?

I find our binary file sizes are just similar, and the 1-2mb is just the package size after compression? I build the releases using https://github.com/joseluisq/rust-linux-darwin-builder, and apply the musl option for Linux builds

**Comment by luckasRanarison** [comment]
> I find our binary file sizes are just similar, and the 1-2mb is just the package size after compression? 

Oh, I didn't realize it was compressed xD. I'll try to add a compression step.

**Comment by luckasRanarison** [comment]
It should theorically work (I hope), you just need to setup the `GITHUB_TOKEN`, and `CRATES_IO_TOKEN` for publishing

**Comment by YiNNx** [comment]
Apologies for the delayed response (have been struggling with some personal matters :(
Now it's time to test the workflow, hoping everything will function as expected :eyes:

**Comment by luckasRanarison** [comment]
> Apologies for the delayed response (have been struggling with some personal matters :(

No problem :)

> Now it's time to test the workflow, hoping everything will function as expected :eyes: 

Waiting for the next release... 

By the way, do you think we could use crossterm? It'd be easy to implement advanced terminal features using crossterm and implement #12.

**Comment by YiNNx** [comment]
> By the way, do you think we could use crossterm? It'd be easy to implement advanced terminal features using crossterm and implement https://github.com/YiNNx/cmd-wrapped/issues/12.

It seems like a good try!

**Comment by YiNNx** [comment]
I removed the armv7 package which is rarely required, and fixed the underline typo for x86_64-apple-darwin package which caused a package generating error. I also changed the auto-release to be marked as draft so that I can edit the Release Note manually.

Now all look good to me :partying_face: Thanks!

image

image

image

**Pull request merged**
