### PR TITLE
feat: atuin support

### LINKED ISSUE #6: Add support for atuin
## What is atuin?

[atuin] is a moder shell history tool. As described in its README: 

> It replaces your existing shell history with a SQLite database, and records additional context for your commands. Additionally, it provides optional and fully encrypted **synchronisation of your history between machines**, via an Atuin server.

## Why need to support it?

I use atuin everyday, and use it to sycnhronize history on company and personal computers. Add support for atuin would make it easier for me to review my usage of terminal history over the past year.

## Specific details

Specific details about support atuin, adding the option `atuin` to `-s` will to fine.

```shell
# specifying the shell or shell history tool [zsh/bash/atuin] 
cargo run -- -s atuin
```

As for obtaining the history list of atuin, can use the following command:

```shell
atuin history list --format "{time}:{command}"
2024-01-05 09:53:57:gs
2024-01-05 09:55:49:ga
2024-01-05 09:55:50:gcn!
2024-01-05 09:55:51:gpf
2024-01-06 02:58:02:python3
2024-01-06 12:08:57:navi
2024-01-06 12:25:09:atuin history list --format "{time}:{command}"
```

[atuin]: https://github.com/atuinsh/atuin

### PR DESCRIPTION
**Pull request by luckasRanarison**
Closes #6.

I'm still hesitating on adding it with `Shell` but the opposite would make things way too complicated. Or maybe we could rename shell to history provider or something...

The error handling is currently bad, I'll try to clean this later and fix the date issue.

I'd like to hear your suggestions on how to improve the error handling in parse functions.

### CODE REVIEW

**Comment by luckasRanarison** [comment]
Like errors are going to be discarded anyways maybe returning `Option<Self>` in the parser functions would be better. This would make things cleaner.

**Comment by kang8** [comment]
Special thanks @luckasRanarison 

Although there is still some struggle to be done in Rust, everything is functioning normally.

image

**Review by YiNNx — DISMISSED** [review]
LGTM. Thanks for taking time to implement the feature!

**Comment by YiNNx** [comment]
>  Or maybe we could rename shell to history provider or something...

You're right, renaming shell to history provider can be a good idea

**Comment by YiNNx** [comment]
> I'd like to hear your suggestions on how to improve the error handling in parse functions.

The current error handling seems to be ok after clean-up

> Like errors are going to be discarded anyways maybe returning Option<Self> in the parser functions would be better. This would make things cleaner.

I prefer returning Result just because it can be used to debug with adding error-printing code in main :thinking:

**Review by YiNNx — APPROVED** [review]
Now it looks great. Thanks again for implementing the atuin support :partying_face:

**Pull request merged**
